---
title: "dasc3240_assignment_1"
output: html_document
date: "2026-03-02"
Name: YANG,Tamoing
Student ID:21062829
---
```{r}
library("usethis")
use_git_config(user.name="wobujiantou",user.email = "tyangay@connect.ust.hk")
```

```{r}
# Load library
library(tidyverse); packageVersion("tidyverse")
```


```{r}
# Load data
data1 <- read.csv("Abbas_2019_TableS4_ed1.csv", row.names = 1)
data2 <- read.csv("Abbas_2019_TableS4_ed2.csv", row.names = 1)

head(data1)
head(data2)
```
```{r}
if (all(rownames(data1)==colnames(data2))){
  print("The rows' names is same as columns' names.")
} else {
  print("The rows' names and columns' names are different.")
}
```


```{r}
age <- data1$AGE_MEDIAN
sum <- apply(data2,2,sum)
```
```{r}
mydata <- data.frame(median_forest_age = as.factor(age), total_tree_abundance = sum)
```

```{r}
age_median <- mydata$median_forest_age
ggplot(mydata, aes(x = median_forest_age, y = total_tree_abundance, color = age_median)) +
  geom_boxplot(outliers = FALSE) +
  geom_jitter(height = 0, width = 0.2, size = 2, alpha = 0.8) +
  labs(title = "Jitterplot and Boxplot of Tree community data in Hong Kong",
    x = "Median forest age (yr)", y = "Total tree abundance (ind.)")
```

```{r}
# change data into compositional data
composition_data2 <- apply(data2, 2, function(x)x/sum(x))
# Scale compositional data
data2_scaled <- t(composition_data2) %>% 
  scale()

head(data2_scaled)

# Check standardization
apply(data2_scaled, 2, mean) %>% round # mean = 0
apply(data2_scaled, 2, sd) %>% round # S.D. = 1

```
```{r}
# Perform PCA
pca_result <- prcomp(data2_scaled)
```

```{r}
# Display the summary of PCA results
summary(pca_result)

# Get PCA scores
pca_scores <- as.data.frame(pca_result$x)

# Get loadings
pca_result$rotation

# Proportion of variation
pca_vars <- pca_result$sdev^2
prop_vars <- pca_vars / sum(pca_vars)
```

```{r}
#PCA Plot
# Combine PCA scores with the Species information
pca_scores$age_median <- mydata$median_forest_age

head(pca_scores)

# Plot the PCA results
pca_scores %>%
  ggplot(aes(x = PC1, y = PC2, color = age_median, shape = age_median)) +
  geom_point(size = 3) +
  labs(title = "PCA of tree community data in Hong Kong",
       x = "PC1 (12.27%)",
       y = "PC2 (9.73%)")
```
```{r}
#NMDS Plot
# Load library
library(vegan) # For community ecology analysis including NMDS

# Set random seed
set.seed(1234) # Better to set a random seed as NMDS includes some random processes

# Do NMDS
nmds_res <- metaMDS(t(composition_data2), # data
                    distance = "bray", # Use Bray-Curtis dissimilarity
                    k = 2) # The number of dimensions
```

```{r}
# Visualize the result using ggplots
nmds_res$points %>% as.data.frame %>%
   ggplot(aes(x = MDS1, y = MDS2)) +
      geom_point(aes(color = age_median,shape = age_median  )) +
      xlab("Axis 1") + ylab("Axis 2") +
      labs(title = "NMDS of tree community data in Hong Kong",
           x = "Axis1",
           y = "Axis2)")
```

